mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/static/templates/
    template-resolver-order: 0
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/