mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/static/templates/
    template-resolver-order: 0
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  mail:
    host: smtp.qq.com
    port: 587
    username: 2228026726@qq.com
    password: ujquaoxpkejwebdi
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
        debug: true
    from: 2228026726@qq.com